version: 7.2x-{build}

image:
- Visual Studio 2015

clone_depth: 1

build_script:
  - git clone --depth=1 https://github.com/bdwgc/libatomic_ops.git -b release-7_2
  - cmake -Denable_gcj_support=ON .
  - cmake --build . --config Debug

test_script:
  - ctest --build-config Debug -V
