# Workflow for checking that Zig build script is formatted properly.
name: zig format check

on: [ push, pull_request ]

jobs:
  build:
    name: Check format of Zig files
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - uses: mlugg/setup-zig@v2

    - name: Run zig fmt (dry run)
      run: zig fmt --check build.zig build.zig.zon
