# Workflow for checking that Zig build script is formatted properly.
name: zig format check

on: [ push, pull_request ]

jobs:
  build:
    name: Check format of Zig files
    runs-on: ubuntu-latest

    strategy:
      matrix:
        zig_version: [ "0.15.2" ]

    steps:
    - uses: actions/checkout@v4

    - uses: korandoru/setup-zig@v1
      with:
        zig-version: ${{ matrix.zig_version }}

    - name: Run zig fmt (dry run)
      run: zig fmt --check build.zig build.zig.zon
